// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbD1_k5KDslcrWAwtGazt78fJKdAzaoTg',
    appId: '1:635099702756:web:6460602b078f93caa1d3f1',
    messagingSenderId: '635099702756',
    projectId: 'colourblindness-c832c',
    authDomain: 'colourblindness-c832c.firebaseapp.com',
    storageBucket: 'colourblindness-c832c.appspot.com',
    measurementId: 'G-JVDMB3M52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBin6Pa-28OQ1_t7XC9a3zCFRhnn0QEr-E',
    appId: '1:635099702756:android:f997b8d356e2006ea1d3f1',
    messagingSenderId: '635099702756',
    projectId: 'colourblindness-c832c',
    storageBucket: 'colourblindness-c832c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWy8FMpA9UaScs2zZp_kAJxKxlvmu-8YU',
    appId: '1:635099702756:ios:08450ad48ce43319a1d3f1',
    messagingSenderId: '635099702756',
    projectId: 'colourblindness-c832c',
    storageBucket: 'colourblindness-c832c.appspot.com',
    iosBundleId: 'com.example.colourBlindness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWy8FMpA9UaScs2zZp_kAJxKxlvmu-8YU',
    appId: '1:635099702756:ios:08450ad48ce43319a1d3f1',
    messagingSenderId: '635099702756',
    projectId: 'colourblindness-c832c',
    storageBucket: 'colourblindness-c832c.appspot.com',
    iosBundleId: 'com.example.colourBlindness',
  );
}
