// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOa4FMU9C3LWXToJ3FgD2ELpgAUJAPSok',
    appId: '1:828306670041:web:3cf5b24b76a203228c59c8',
    messagingSenderId: '828306670041',
    projectId: 'colour-blindness-5be13',
    authDomain: 'colour-blindness-5be13.firebaseapp.com',
    storageBucket: 'colour-blindness-5be13.appspot.com',
    measurementId: 'G-WE6RJLMPN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMHiQ5bvcpIHbNkwWc-Fi3Xf6292YxbY',
    appId: '1:828306670041:android:68004b8c7d0f5dee8c59c8',
    messagingSenderId: '828306670041',
    projectId: 'colour-blindness-5be13',
    storageBucket: 'colour-blindness-5be13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAi7HCxsP6BymDPeFulB3eHo-vFMf7-0',
    appId: '1:828306670041:ios:ee81132477263b368c59c8',
    messagingSenderId: '828306670041',
    projectId: 'colour-blindness-5be13',
    storageBucket: 'colour-blindness-5be13.appspot.com',
    iosClientId: '828306670041-dotvgf6t55l79ap4ofm53se94kf9ltji.apps.googleusercontent.com',
    iosBundleId: 'com.example.colourBlindness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAi7HCxsP6BymDPeFulB3eHo-vFMf7-0',
    appId: '1:828306670041:ios:ee81132477263b368c59c8',
    messagingSenderId: '828306670041',
    projectId: 'colour-blindness-5be13',
    storageBucket: 'colour-blindness-5be13.appspot.com',
    iosClientId: '828306670041-dotvgf6t55l79ap4ofm53se94kf9ltji.apps.googleusercontent.com',
    iosBundleId: 'com.example.colourBlindness',
  );
}
